var mongoose = require('mongoose');

var GameSchema = new mongoose.Schema({
  // _id, generated by mongo
  event: {type: mongoose.Schema.Types.ObjectId, ref: "Event"},

  team_a: {type: mongoose.Schema.Types.ObjectId, ref: "Team", required: true},
  team_b: {type: mongoose.Schema.Types.ObjectId, ref: "Team", required: true},
  team_a_score: {type: Number, required: true},
  team_b_score: {type: Number, required: true},

  // 0 or 1
  rt_snitch: {type: String, match: /[ab]/, required: true},
  ot_snitch: {type: String, match: /[ab]/, default: null},
  sd_snitch: {type: String, match: /[ab]/, default: null},

  // game time, in seconds
  duration: Number,
  mutli_league: {type: Boolean, default: false},
  
  head_referee: {type: mongoose.Schema.Types.ObjectId, ref: "Person"},
  snitch: {type: mongoose.Schema.Types.ObjectId, ref: "Person"},

  forfeit: {type: Boolean, default: false},

  etc: Object
});

mongoose.model('Game', GameSchema);