var mongoose = require('mongoose');

var LeagueSchema = new mongoose.Schema({
  // _id, generated by mongo
  name: String,
  // ISO 3 letter country code
  code: String,
  subregions: [String],
  // rulebook? string?
  etc: Object
});

mongoose.model('League', LeagueSchema);