var mongoose = require('mongoose');

var PersonSchema = new mongoose.Schema({
  // _id, generated by mongo
  name: {type: String, reqiured: true},
  email: String,
  created: {type: Date, default: Date.now()},
  certifications: {
    ar: {type: Boolean, default: false},
    sr: {type: Boolean, default: false},
    hr_written: {type: Boolean, default: false},
    hr_field: {type: Boolean, default: false},
    td: {type: Boolean, default: false}
  },
  // league: {type: mongoose.Schema.Types.ObjectId, ref: "League", required: true},
  team: {type: mongoose.Schema.Types.ObjectId, ref: "Team"},
});

mongoose.model('Person', PersonSchema);