var mongoose = require('mongoose');
// roster of refs and stuff

// this is just so there's a little less copy/paste. Er, it's shorter.
var personReference = new mongoose.Schema({
  type: mongoose.Schema.Types.ObjectId, ref: "Person"
});

var DetailSchema = new mongoose.Schema({
  // _id, generated by mongo
  hr: personReference,
  sr: personReference,
  ar1: personReference,
  ar2: personReference,
  scorekeepers: {type: mongoose.Schema.Types.ObjectId, ref: "Team"},
  goal_refs: {type: mongoose.Schema.Types.ObjectId, ref: "Team"},
  pool: String,
  round: Number,
  pitch: Number
});

mongoose.model('Detail', DetailSchema);