var mongoose = require('mongoose');

var GameSchema = new mongoose.Schema({
  // _id, generated by mongo
  event: {type: mongoose.Schema.Types.ObjectId, ref: "Event"},

  team_a: {type: mongoose.Schema.Types.ObjectId, ref: "Team", required: true},
  team_b: {type: mongoose.Schema.Types.ObjectId, ref: "Team", required: true},
  // scores not required so that we can use these to schedule
  team_a_score: {type: Number},
  team_b_score: {type: Number},

  // team_a's _id|team_b's _id
  // makes document a little bigger, but aggregation is easier

  // rt snitch should be required. maybe a difference between game schedule and game result?
  rt_snitch: {type: mongoose.Schema.Types.ObjectId, ref: "Team", default: null},
  ot_snitch: {type: mongoose.Schema.Types.ObjectId, ref: "Team", default: null},
  sd_snitch: {type: mongoose.Schema.Types.ObjectId, ref: "Team", default: null},

  // game time, in seconds
  duration: Number,

  // this is denoted by the leagues of the teams
  // mutli_league: {type: Boolean, default: false},
  
  head_referee: {type: mongoose.Schema.Types.ObjectId, ref: "Person"},
  snitch: {type: mongoose.Schema.Types.ObjectId, ref: "Person"},

  forfeit: {type: Boolean, default: false},

  // this was for storing sr, ar info, but we don't need that in the schema?
  // etc: mongoose.Schema.Types.Mixed
});

mongoose.model('Game', GameSchema);