var mongoose = require('mongoose');

var LeagueSchema = new mongoose.Schema({
  // _id, generated by mongo
  name: {type: String, required: true}, 
  abbreviation: String, 
  // ISO 3 letter country code
  code: {type: String, required: true}, 
  subregions: [String],
  // rulebook? string?
  // notes on weird rules like off-pitch seeking?
});

mongoose.model('League', LeagueSchema);