var mongoose = require('mongoose');

var PersonSchema = new mongoose.Schema({
  // _id, generated by mongo
  name: {type: String, reqiured: true},
  email: String,
  // created: {type: Date, default: Date.now()},
  // this could be moved to a different collection and just linked, but that's not mongo
  certifications: {
    ar: {type: Boolean, default: false},
    sr: {type: Boolean, default: false},
    hr_written: {type: Boolean, default: false},
    hr_field: {type: Boolean, default: false},
    td: {type: Boolean, default: false}
  },
  // there are enough multiple team affiliations that it's worth having an arrary. The first spot will always be for the primary team
  teams: [{type: mongoose.Schema.Types.ObjectId, ref: "Team"}],
  requests: {type: [{type: mongoose.Schema.Types.ObjectId, ref: "Team"}], default: []}

});

mongoose.model('Person', PersonSchema);