var mongoose = require('mongoose');

var TeamSchema = new mongoose.Schema({
  // _id, generated by mongo
  name: {type: String, required: true, trim: true},
  short_name: {type: String, maxlength: 4, required: true, uppercase: true, unique: true, trim: true},
  league: {type: mongoose.Schema.Types.ObjectId, ref: "League"}
  // stored as a string? or actual geo data? or just city/state(province)
  // not sure we actually need it at all
  // location: {type: String}

});

mongoose.model('Team', TeamSchema);